# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
  branches:
    include:
    - models-package  # Replace with the branch name you want to clone

pr:
  branches:
    include:
    - models-package  # Replace with the branch name you want to clone
